# Generated by Django 5.1.2 on 2024-10-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='registred',
            new_name='registered',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('agent', 'agent'), ('client', 'client')], default='client', max_length=15),
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
