# Generated by Django 5.1.2 on 2024-10-28 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_client'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='Client',
        ),
    ]
