# Generated by Django 5.1.2 on 2024-10-28 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_client_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(max_length=100, unique=True)),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Occupation',
            },
        ),
        
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=9, unique=True)),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL)),
                ('occupation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='api.occupation')),
            ],
            options={
                'db_table': 'Agent',
            },
        ),
    ]
