# Generated by Django 5.1.2 on 2024-10-28 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_agent_occupation_alter_client_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='occupation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='api.occupation'),
        ),
    ]
