# Generated by Django 5.1.2 on 2024-10-30 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_agent_occupation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='img')),
                ('priority', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='Media', max_length=20)),
                ('status', models.CharField(choices=[('cerrado', 'Cerrado'), ('en proceso', 'En proceso'), ('abierto', 'Abierto')], default='Abierto', max_length=20)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateTimeField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='api.agent')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='api.client')),
            ],
            options={
                'db_table': 'Ticket',
            },
        ),
    ]
