# Generated by Django 5.1.2 on 2024-10-30 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='creation_date',
            new_name='registered_date',
        ),
    ]
