# Generated by Django 5.1.2 on 2024-11-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_creation_date_ticket_registered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('notificacion', 'Notificacion'), ('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('cerrado', 'Cerrado')], default='notificacion', max_length=20),
        ),
    ]
