# Generated by Django 5.1.2 on 2024-11-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_ticket_priority_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
