# Generated by Django 5.1.2 on 2024-11-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_ticket_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('notificacion', 'Notificacion'), ('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('cerrado', 'Cerrado')], default='Notificacion', max_length=20),
        ),
    ]
