# Generated by Django 5.1.2 on 2024-11-04 18:04

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='000-000-0000', max_length=128, region='PE', unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='000-000-0000', max_length=128, region='PE', unique=True),
        ),
    ]
