# Generated by Django 5.1.2 on 2024-11-04 20:36

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_agent_phone_alter_client_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='000-000-000', max_length=128, region='PE', unique=True),
        ),
    ]
